apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2 
kind: StatefulSet 
metadata: 
  name: java-deployment-new
spec: 
  serviceName: java-deployment-new
  replicas: 2
  selector: 
    matchLabels: 
      app: javanew
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: javanew 
    spec: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: environment
                operator: In
                values:
                - "newaks"
      containers: 
      - name: javanew 
        image: imageacr.azurecr.io/csandhya8/springbootmavenjunitsample:78
        resources:
          limits:
           cpu: "0.7"
          requests:
           cpu: "0.3"
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: autodeploy      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-service-new
spec: 
  selector: 
    app: javanew 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
---
apiVersion: autoscaling/v2beta1
#apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: java-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: StatefulSet
    name: java-deployment-new
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
